version: "3.7"

# ports used:
# 80 -> site wordpress
# 82 -> site symfony
# 3000 -> rocketchat
# 3306 -> mariadb
# 9000 -> PHPmyadmin

services:
  # symfony
  siteSymfony:
    image: "qwertyjuju/deb_symfony:1.0"
    container_name: serv_web
    restart: on-failure
    stdin_open: true
    tty: true
    environment:
      - GIT_REPO=https://github.com/qwertyjuju/site_presentation
    ports:
      - 82:80
    networks:
      - servnet

  # symfony and wordpress database (mariadb)
  symfonydb:
    image: "mariadb:latest"
    container_name: symfonydb
    volumes:
      - .\repDB:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=blog_user
      - MARIADB_DATABASE=mariadb
      - MARIADB_PASSWORD=S3Cr3T!
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    networks:
      - servnet

  # PHPmyAdmin
  symfony_db_admin:
    image: "phpmyadmin:latest"
    container_name: symfony_db_admin
    environment:
      - PMA_HOST=symfonydb
    ports:
      - 9000:80
    networks:
      - servnet
    depends_on:
      - symfonydb

  # Wordpress
  wordpress:
    image: "wordpress:latest"
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=symfonydb
      - WORDPRESS_DB_USER=blog_user
      - WORDPRESS_DB_PASSWORD=S3Cr3T!
      - WORDPRESS_DB_NAME=mariadb
    ports:
      - 80:80
    volumes:
      - .\repWP:/var/www/html
    depends_on:
      - symfonydb
    links:
      - symfonydb
    networks:
      - servnet

  # rocketchat
  rocketchat:
    image: rocket.chat:latest
    restart: on-failure
    container_name: rocketchat
    environment:
      - MONGO_URL=mongodb://mongodb:27017/local?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local?replicaSet=rs0
      - ROOT_URL=http://rocketchat:3000
      - PORT=3000
    networks:
      - servnet
    links:
      - mongodb
    depends_on:
      - mongodb   
    ports:
      - 3000:3000
  
  # mongodb for rocketchat
  mongodb:
    image: bitnami/mongodb:4.4
    container_name: mongodb
    environment:
      - MONGODB_DATABASE=mongodb
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_ENABLE_JOURNAL=true
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - servnet
networks:
  servnet:
    name: servnet